export { default as App } from '@/pages/app';
export { default as Register } from '@/pages/auth/register';
export { default as Login } from '@/pages/auth/login';
export { default as ForgotPassword } from '@/pages/auth/forgot-password';
export { default as ResetPassword } from '@/pages/auth/reset-password';
export { default as TokenExpired } from '@/pages/auth/token-expired';
export { default as Home } from '@/pages/home';
export { default as About } from '@/pages/about';
export { default as Contact } from '@/pages/contact';
