import * as dotenv from 'dotenv';
dotenv.config();

const {
	BASE_URL,
	DATABASE_URL,
	ACCESS_TOKEN_SECRET_KEY,
	FORGOT_PASSWORD_TOKEN_SECRET_KEY,
	CLIENT_URL,
	SENDER_MAIL,
	APP_PASS,
} = process.env;

export {
	BASE_URL,
	DATABASE_URL,
	ACCESS_TOKEN_SECRET_KEY,
	FORGOT_PASSWORD_TOKEN_SECRET_KEY,
	CLIENT_URL,
	SENDER_MAIL,
	APP_PASS,
};
